export const Received_USER_DATA_GET = "Received_USER_DATA_GET";
export const GET_LOADING_USER_DATA_GET = "GET_LOADING_USER_DATA_GET";
export const ERROR_LOADING_USER_DATA_GET = "ERROR_LOADING_USER_DATA_GET";
